//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attend
    {
        public int Class_ID { get; set; }
        public int Stu_ID { get; set; }
        public Nullable<int> Att_Interactions { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
